source 'https://rubygems.org'



  gem 'selenium-webdriver', '~>3.10.0'
  gem 'rspec', '~> 3.3.0'
  gem 'rspec-expectations'
  gem 'rspec-retry'
  gem 'capybara'
  gem 'nokogiri', '~> 1.8.1'
  gem 'chromedriver-helper', '0.0.8'
  gem 'geckodriver-helper'
  gem 'poltergeist', '1.6.0'
  gem 'smarter_csv', '1.0.19'
  gem 'json-schema', '2.6.2'
  gem 'require_all'
  gem 'typhoeus'
  gem 'page-object', '~> 2.0'
  gem 'cucumber'
  gem 'site_prism'
  gem 'rspec-support', '~> 3.3'
  gem 'sauce_whisk', '~> 0.1.0'
  gem 'sauce'
  gem 'parallel_tests'
  gem 'cmdparse', '~> 3.0', '>= 3.0.3'
  gem 'rake-rspec'
  gem 'parallel-rspec'
  gem 'restforce', '~> 2.4'
  gem 'faker'
  gem 'activesupport', '~> 5.0', '>= 5.0.0.1'
  gem 'ruby-enum', '~> 0.7.1'
  gem 'launchy', '~> 2.4', '>= 2.4.3'
  gem 'typhoeus'
